### ISSUE TITLE
UI: World Whyd Ranking page is slow to display data => user notice should be added

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#21]
cf https://openwhyd.org/discover/ranking

**Comment by compiuta** [comment]
It looks like the page was actually throwing an error of "too many redirects" that prevented the page from loading.

I removed the redirect code and the page is now loading for guest users and signed in users.

**Comment by adrienjoly** [comment]
@compiuta were you able to reproduce that (too many redirects) locally?

on my side, I don't see it...

=> I may be wrong but I have a different hypothesis about the source of the issue: computing the ranking has become slow because the number of user and tracks has grown, and the algorithm does not scale well.

what do you think ?

**Comment by compiuta** [comment]
The redirect error only happens when you are logged out and I did notice it locally as well.
 
![Screenshot from 2020-04-12 12-57-47](https://user-images.githubusercontent.com/13477167/79078477-84638800-7cbd-11ea-8b2f-348d066d296a.png)

Also how long should the ranking results take to load? It takes about 2 seconds for me while logged in.
