### ISSUE TITLE
where can I get  WHYD_ADMIN_OBJECTID ?

### ISSUE THREAD

**Issue by umangoo** [openwhyd/openwhyd#24]
HI!
Where can I get WHYD_GENUINE_SIGNUP_SECRET、WHYD_SESSION_SECRET and WHYD_ADMIN_OBJECTID ？

How to set Environment variables? 

Is there a site description setting environment here?

Looking forward to your reply. Best wishes

**Comment by adrienjoly** [comment]
Hi @umangoo !

You can use any value for these 3 environment variables.

On openwhyd.org, we keep WHYD_GENUINE_SIGNUP_SECRET and WHYD_SESSION_SECRET as a secret for security reasons. (e.g. to prevent hackers from forging accounts and sessions without authorization from our server, including from our official iOS app)

After deploying openwhyd to your own server, and creating a user account for yourself, you can set its user id to WHYD_ADMIN_OBJECTID, in order to give admin privileges to this account.

Does that answer your questions?

**Comment by umangoo** [comment]
thanks very much
