### ISSUE TITLE
API endpoint blocked by CORS policy for localhost

### ISSUE THREAD

**Issue by olga-brushuk** [openwhyd/openwhyd#331]
Trying to fetch Openwhyd Data Export API https://openwhyd.org/hot?format=json using React with JS fetch() method (https://reactjs.org/docs/faq-ajax.html), but it doesn't run on localhost:3000, it gives the following error:

`Access to fetch at 'https://openwhyd.org/hot?format=json' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Do you have any headers added to the API endpoints to allow usage on localhost?

 - OS: maciOS Mojave Version 10.14.5
 - Browser: Chrome Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by adrienjoly** [comment]
Hi Olga, thanks for reaching out!

I don't remember having defined a CORS policy on Openwhyd.

I agree that it may make sense to allow agents to send requests to the Data Export API, at least from localhost.

Would you be interested to propose a Pull Request, in order to support it?

**Comment by adrienjoly** [comment]
Also, I'd love to know what you intend to build with Openwhyd's API, @olga-brushuk, if you don't mind :-)
(just curious, and maybe I can help)

**Comment by victorWeiFreelancer** [comment]
according to this [https://stackoverflow.com/questions/36878255/allow-access-control-allow-origin-header-using-html5-fetch-api](https://stackoverflow.com/questions/36878255/allow-access-control-allow-origin-header-using-html5-fetch-api), cors needs to be activated from server side. The fetch config { mode: 'no-cors'} is not going to help. I'm trying to add cors on server side

**Comment by adrienjoly** [comment]
Thank you for your help, Victor! 🙌

FYI, I just found out that, even if we enable CORS for this endpoint, Chrome does not support sending AJAX requests from `localhost`, even if CORS was enabled for `*`. (see https://stackoverflow.com/questions/10883211/deadly-cors-when-http-localhost-is-the-origin and https://bugs.chromium.org/p/chromium/issues/detail?id=67743#c47)

Workarounds:
- start Chrome with the `--allow-file-access-from-files --disable-web-security` flags
- use another browser

**Comment by olga-brushuk** [comment]
Hi Adrien,

Many thanks for looking into it and fixing it! I got some recommendations as well from StackOverflow about Chrome support. I'll try to check the application in the next couple of days and will see how it all works, will give my feedback then.

Thanks, Olga

**Comment by victorWeiFreelancer** [comment]
Hello Olga,

as is hinted by the stackoverflow link and the link to the chrome ticket, it is actually a known issue which comes from the browsers such as Chrome which has binary security logic that blocks AJAX request from localhost. I tried the workaround on my local machine by giving the below sample command in terminal (MacOS):
`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --disable-web-security --user-data-dir="whatever"`
and the fetch gets through when querying the remote endpoint:
![Screenshot 2020-07-31 at 09 45 25](https://user-images.githubusercontent.com/46331896/89012608-bf440700-d312-11ea-8122-5f0ddaed51d6.png)
On my machine the same issue happens also for Safari:
<img width="701" alt="Screenshot 2020-07-31 at 09 47 50" src="https://user-images.githubusercontent.com/46331896/89012732-ea2e5b00-d312-11ea-99cb-d092a23045e1.png">
Note that the fetch for the remote site - with no cors specified gets through with the workaround indicates that it's not blocked by cors policy on server side. I also tested on fetching into locally deployed Openwhyd with the 'cors' package added. But it doesn't make a difference if the workaround is not used for chrome.

If you agree with the above, I think we might as well close the ticket because it's a known issue. We will definitely add cors later for the app but with a well-rounded scope. 

Feel free if anything isn't clear.

Cheers,
Victor
