### ISSUE TITLE
BUG: youtube track (with "-") cannot be added from Youtube page nor copy-pasting its URL

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#74]
URL: https://www.youtube.com/watch?v=-gOK9LjTtl8

Hypothesis: the id of the video starting with a "-" is not recognized as a valid id.

If so, the playemjs dependency may have to be upgraded.

**Comment by adrienjoly** [comment]
If you'd like to try solving this bug, I'd be happy to help => let me know!

**Comment by Marinlemaignan** [comment]
It's bizarre because the video can still be played from the player even though no informations seem to be gathered and the search popup are empty.. Then i realised "data on our side" with still being returned, but no track infos.. This seemed to be an issue with youtube's v3 API..
I finally checked out online and it's a formatting 'error' for the `query` bit in their api, here:
```
// actually the, var query = "-gOK9LjTtl8"
// but if replaced with full url like "https://www.youtube.com/watch?v=-gOK9LjTtl8" it works
gapi.client.youtube.search.list({
        part: 'snippet',
        q: query,
        type : "video",
        maxResults : limit,
      })
```

**Comment by adrienjoly** [comment]
current status: waiting for Marin to double-check my PR before merging fix to `master` and pushing to production

**Comment by adrienjoly** [comment]
Pushing to production. We'll see if it solves our users' problem.

**Comment by adrienjoly** [comment]
Working for me. Notified users on Facebook: https://www.facebook.com/groups/openwhyd/permalink/1922777248003825/
