### ISSUE TITLE
Better genre detection and track recommendation #ML #data

### ISSUE THREAD

**Issue by adrienjoly** [openwhyd/openwhyd#83]
For music lovers, discovering new music is essential.

Spotify is well known for the quality of their "Discover Weekly" playlist, containing a personalised selection of tracks based on your listening history.

On Openwhyd, current ways to discover music are:

1. listening to your stream, after having followed users with similar musical taste;
2. or listening to hot tracks, which are classified by genres.

The first way is purely relying on humans and luck.

The second way relies on a list of 16 genres (a quite limited and vague selection of genres), in which popular tracks are classified, based on the names of the playlists that hold them. This kinda works but it's far from perfect. For example, we had to create a [hard-coded rule](https://github.com/openwhyd/openwhyd/blob/df498a128f3a62685ca64f726b746242e4bb3094/whydJS/app/models/plTags.js#L30) to prevent Daft Punk songs from being recognised as Punk Rock music! 

In order to discover new music by discovering relevant people to follow, we had also experienced showing a [measure of profile similarity](https://github.com/openwhyd/openwhyd/blob/d5935d7f1001e682174fdcba6b79cbda23e97ecc/whydJS/public/js/discover.js#L109), but it was only based on the number of artists that were added by both users.

=> Anyone interested in exploring new ways to discover music on Openwhyd?

**Comment by adrienjoly** [comment]
Examples that could be applied to Openwhyd:

- [Building a Music Recommender with Deep Learning – Matt Murray](http://mattmurray.net/building-a-music-recommender-with-deep-learning/)
- [Finding the genre of a song with Deep Learning — A.I. Odyssey part. 1](https://chatbotslife.com/finding-the-genre-of-a-song-with-deep-learning-da8f59a61194)

#deeplearning

**Comment by Marinlemaignan** [comment]
This is a rather exciting feature to add!
I was thinking that, maybe, we could replace plTags.js by another db backedup service that would first ask [discogs' api](https://github.com/buntine/discogs) infos about a track/album/artist's metadata, and then store them back for later use, instead of being hardcoded as it is now. So we can then build something that would be able to evolve bits by bits. Also mongodb's perfect for this kind of job.

**Comment by adrienjoly** [comment]
Hi @Marinlemaignan !

I'd be happy to replace plTags.js when we have a fully-functional solution that is better than the current one, while maintaining:
- user satisfaction on the hot tracks page (which is also openwhyd's landing page)
- and relevance of the users that are recommended based on selected genres, during user onboarding (also fed by plTags)

One way we could transition gently to a new system:
- the new system (e.g. based on discogs) is developed outside of openwhyd's repo,
- inspired by the use cases provided above, automated tests are written to ensure that the new system works as expected (or better),
- when hosted online, the new system's database could be populated at the same time as plTags's system does, by pluging a web-hook (or something like that).

What do you think?
Are you interested in working on this?

**Comment by SkinyMonkey** [comment]
I have experimented extensively with discog's API.

It's very complete, extremely promising but ... the number of request is of 60 requests .. per minute.

https://www.discogs.com/developers/#page:home,header:home-rate-limiting

There is no way to go around this. A partnership would be the only solution and I doubt that they would be attracted by a partnership that does not bring them anything.

What we could do is identify albums and point to their products/sellings. They would not split in such a big showcase as openwhyd.

A solution is to host their database. There is docker images to download their monthly dump and index it in mongodb.
A mongo-connector to an elasticsearch database then allow us to get the extra performance to be efficient on the lookup.
I tried, it was working well.

But even then a few other problems arise : 
- youtube/soundcloud names are not always the right ones, mispelled etc
- identify the right album from discog is sometime difficult, i spent a lot of time on this.
- the images of the albums are not available in the dump, would be cool to display it instead of the youtube artwork for example
 - the links to youtube videos linked to the album
    yes .. yes they have that and it would be an amazing feature!
    imagine, you post a track and bam! You get other tracks from the same album
    but they are not available in the dump

A solution that I studied would be scraping ... but they wouldn't like it and what a dirty solution.

I'm not saying it's impossible, just that it's not a bulletproof approach.

**Comment by adrienjoly** [comment]
Thanks for sharing our ideas and notes with us, @SkinyMonkey !

**Comment by adrienjoly** [comment]
WIP:

- [Analytics / BI: know our users (and openwhyd usage) better · Issue #107 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/107)
- [Analytics / BI: count track playback errors, study the causes, increase success rate · Issue #88 · openwhyd/openwhyd](https://github.com/openwhyd/openwhyd/issues/88)

Florent Piétot is currently analysing Openwhyd's data set, and thinking of ways to leverage it (e.g. use clustering and/or machine learning techniques for better genre detection and music recommendation).

**Comment by adrienjoly** [comment]
During a "Hackergarten" meetup in Paris, Mihangy, Damien and I wrote a script that turns `playlog.json.log` to a anonymised csv file in which each line associates a user (identified by a number) to a youtube track id that the user listened to.

👉 https://github.com/openwhyd/openwhyd/commit/2c095d22a7245fa67964ed30c0273300ce9db8d2

The goal was to provide a starting point for the development of a music recommendation algorithm based on Openwhyd's playback logs, while preserving the privacy of its users. (i.e. data anonymisation)

Next steps:
- cluster similar songs by similarity, e.g. groups of tracks that we're listened by more than one user
- build a mini website that would recommend tracks, based on a user-given youtube video
- build a mini website that would recommend tracks and openwhyd users to subscribe to, based on the user's openwhyd profile
- integrate it as a discovery feature on openwhyd.org

**Comment by adrienjoly** [comment]
This also may help: https://github.com/trekhleb/homemade-machine-learning (examples of machine learning techniques in Python, based on Andrew Ng's MOOC)

**Comment by adrienjoly** [comment]
During Hackergarten meetup, Sébastien Treguer suggested the following next step:

> First easy step, implement a collaborative filtering for recommendation, with a matrix of users (in rows) and content like videos (in columns)
> 
> http://surpriselib.com/

**Comment by adrienjoly** [comment]
For reference: Mihangy is experimenting with Jupyter Notebooks and SurpriseLib. He opened a [google group](https://groups.google.com/forum/#!forum/openwhyd-pywrkgroup) to discuss data analysis tasks on openwhyd's data using those tools.

**Comment by adrienjoly** [comment]
For reference, I published a 700MB history/playlog file in https://github.com/openwhyd/openwhyd-data

**Comment by adrienjoly** [comment]
This list of best practices could help: https://github.com/microsoft/recommenders

**Comment by adrienjoly** [comment]
Music genre detection and genre-based streams were removed in #399. => Closing.
